# Generated by Django 2.1.7 on 2019-03-28 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='incomingRequests',
            field=models.ManyToManyField(blank=True, related_name='incoming_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='outgoingRequests',
            field=models.ManyToManyField(blank=True, related_name='outgoing_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
