# Generated by Django 2.1.7 on 2019-03-07 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190221_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='host',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Node'),
        ),
    ]
