<<<<<<< HEAD
# Generated by Django 2.1.7 on 2019-03-29 21:20
=======
# Generated by Django 2.1.7 on 2019-03-29 21:14
>>>>>>> 3f2a6afdbaa0838f88d9acfbf1e568719e180c99

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='local',
            field=models.BooleanField(default=True),
        ),
    ]
