# Generated by Django 2.1.7 on 2019-04-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
