# Generated by Django 2.1.7 on 2019-04-04 18:32

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_node_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedServer',
            fields=[
            ],
            options={
                'verbose_name': 'connected server',
                'verbose_name_plural': 'connected servers',
                'permissions': (('can_access_api', 'Can access API'),),
                'proxy': True,
                'indexes': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
    ]
