# Generated by Django 2.1.7 on 2019-02-21 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('content_type', models.CharField(choices=[('MKD', 'text/markdown'), ('TXT', 'text/plain'), ('APP', 'application/base64'), ('PNG', 'imgage/png;base64'), ('JPG', 'image/jpeg;base64')], default=posts.utils.ContentType('TXT'), max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('source', models.URLField()),
                ('origin', models.URLField()),
                ('description', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('MKD', 'text/markdown'), ('TXT', 'text/plain'), ('APP', 'application/base64'), ('PNG', 'imgage/png;base64'), ('JPG', 'image/jpeg;base64')], default=posts.utils.ContentType('TXT'), max_length=3)),
                ('visiblilty', models.CharField(choices=[('PUBL', 'Public'), ('FOAF', 'Friend of a Friend'), ('PRIV', 'Private'), ('SERV', 'Home Server Only')], default=posts.utils.Visibility('PUBL'), max_length=4)),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(to='posts.Categories')),
                ('visible_to', models.ManyToManyField(related_name='visible_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
        migrations.AddField(
            model_name='attachments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
