# Generated by Django 2.1.7 on 2019-04-04 00:06

from django.db import migrations, models
import django.utils.timezone
import posts.utils


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190403_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBL', 'Public'), ('FOAF', 'Friend Of A Friend'), ('PRIV', 'Private'), ('SERV', 'Home Server Only'), ('FRND', 'Friends Only')], default=posts.utils.Visibility('PUBL'), max_length=4),
        ),
    ]
