# Generated by Django 2.1.7 on 2019-04-04 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20190403_1412'),
        ('posts', '0008_auto_20190404_0006'),
    ]

    operations = [
    ]
